<?php
namespace App\Controller\Admin;

use App\Form\Admin\TestType;
use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\Request;

class TestController extends CRUDController
{
    public function createAction()
    {
        $form = $this->createForm(TestType::class, []);

        if ($form->isSubmitted() && $form->isValid()) {
            // ... do your form processing, like saving the Task and Tag entities
        }

        return $this->renderWithExtraParams('admin/test_edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function listAction()
    {
        return parent::listAction(); // TODO: Change the autogenerated stub
    }
}